#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOIA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ioDB")]
	public partial class DDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertBestimmungsort(Bestimmungsort instance);
    partial void UpdateBestimmungsort(Bestimmungsort instance);
    partial void DeleteBestimmungsort(Bestimmungsort instance);
    partial void InsertKunde(Kunde instance);
    partial void UpdateKunde(Kunde instance);
    partial void DeleteKunde(Kunde instance);
    partial void InsertTeilschritt(Teilschritt instance);
    partial void UpdateTeilschritt(Teilschritt instance);
    partial void DeleteTeilschritt(Teilschritt instance);
    partial void InsertMN_VerfahrenAuftrag(MN_VerfahrenAuftrag instance);
    partial void UpdateMN_VerfahrenAuftrag(MN_VerfahrenAuftrag instance);
    partial void DeleteMN_VerfahrenAuftrag(MN_VerfahrenAuftrag instance);
    partial void InsertVerfahren(Verfahren instance);
    partial void UpdateVerfahren(Verfahren instance);
    partial void DeleteVerfahren(Verfahren instance);
    partial void InsertMaterial(Material instance);
    partial void UpdateMaterial(Material instance);
    partial void DeleteMaterial(Material instance);
    partial void InsertAuftrag(Auftrag instance);
    partial void UpdateAuftrag(Auftrag instance);
    partial void DeleteAuftrag(Auftrag instance);
    #endregion
		
		public DDataContext() : 
				base(global::HOIA.Properties.Settings.Default.ioDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bestimmungsort> Bestimmungsort
		{
			get
			{
				return this.GetTable<Bestimmungsort>();
			}
		}
		
		public System.Data.Linq.Table<Kunde> Kunde
		{
			get
			{
				return this.GetTable<Kunde>();
			}
		}
		
		public System.Data.Linq.Table<Teilschritt> Teilschritt
		{
			get
			{
				return this.GetTable<Teilschritt>();
			}
		}
		
		public System.Data.Linq.Table<MN_VerfahrenAuftrag> MN_VerfahrenAuftrag
		{
			get
			{
				return this.GetTable<MN_VerfahrenAuftrag>();
			}
		}
		
		public System.Data.Linq.Table<Verfahren> Verfahren
		{
			get
			{
				return this.GetTable<Verfahren>();
			}
		}
		
		public System.Data.Linq.Table<Material> Material
		{
			get
			{
				return this.GetTable<Material>();
			}
		}
		
		public System.Data.Linq.Table<Auftrag> Auftrag
		{
			get
			{
				return this.GetTable<Auftrag>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bestimmungsort")]
	public partial class Bestimmungsort : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Anschrift;
		
		private string _PLZ;
		
		private string _Stadt;
		
		private string _Land;
		
		private EntitySet<Auftrag> _Auftrag;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAnschriftChanging(string value);
    partial void OnAnschriftChanged();
    partial void OnPLZChanging(string value);
    partial void OnPLZChanged();
    partial void OnStadtChanging(string value);
    partial void OnStadtChanged();
    partial void OnLandChanging(string value);
    partial void OnLandChanged();
    #endregion
		
		public Bestimmungsort()
		{
			this._Auftrag = new EntitySet<Auftrag>(new Action<Auftrag>(this.attach_Auftrag), new Action<Auftrag>(this.detach_Auftrag));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anschrift", DbType="VarChar(50)")]
		public string Anschrift
		{
			get
			{
				return this._Anschrift;
			}
			set
			{
				if ((this._Anschrift != value))
				{
					this.OnAnschriftChanging(value);
					this.SendPropertyChanging();
					this._Anschrift = value;
					this.SendPropertyChanged("Anschrift");
					this.OnAnschriftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLZ", DbType="VarChar(50)")]
		public string PLZ
		{
			get
			{
				return this._PLZ;
			}
			set
			{
				if ((this._PLZ != value))
				{
					this.OnPLZChanging(value);
					this.SendPropertyChanging();
					this._PLZ = value;
					this.SendPropertyChanged("PLZ");
					this.OnPLZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stadt", DbType="VarChar(50)")]
		public string Stadt
		{
			get
			{
				return this._Stadt;
			}
			set
			{
				if ((this._Stadt != value))
				{
					this.OnStadtChanging(value);
					this.SendPropertyChanging();
					this._Stadt = value;
					this.SendPropertyChanged("Stadt");
					this.OnStadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land", DbType="VarChar(50)")]
		public string Land
		{
			get
			{
				return this._Land;
			}
			set
			{
				if ((this._Land != value))
				{
					this.OnLandChanging(value);
					this.SendPropertyChanging();
					this._Land = value;
					this.SendPropertyChanged("Land");
					this.OnLandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bestimmungsort_Auftrag", Storage="_Auftrag", ThisKey="Id", OtherKey="Id_Bestimmungsort")]
		public EntitySet<Auftrag> Auftrag
		{
			get
			{
				return this._Auftrag;
			}
			set
			{
				this._Auftrag.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Auftrag(Auftrag entity)
		{
			this.SendPropertyChanging();
			entity.Bestimmungsort = this;
		}
		
		private void detach_Auftrag(Auftrag entity)
		{
			this.SendPropertyChanging();
			entity.Bestimmungsort = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kunde")]
	public partial class Kunde : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Anschrift;
		
		private string _PLZ;
		
		private string _Stadt;
		
		private string _Land;
		
		private EntitySet<Auftrag> _Auftrag;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAnschriftChanging(string value);
    partial void OnAnschriftChanged();
    partial void OnPLZChanging(string value);
    partial void OnPLZChanged();
    partial void OnStadtChanging(string value);
    partial void OnStadtChanged();
    partial void OnLandChanging(string value);
    partial void OnLandChanged();
    #endregion
		
		public Kunde()
		{
			this._Auftrag = new EntitySet<Auftrag>(new Action<Auftrag>(this.attach_Auftrag), new Action<Auftrag>(this.detach_Auftrag));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anschrift", DbType="VarChar(50)")]
		public string Anschrift
		{
			get
			{
				return this._Anschrift;
			}
			set
			{
				if ((this._Anschrift != value))
				{
					this.OnAnschriftChanging(value);
					this.SendPropertyChanging();
					this._Anschrift = value;
					this.SendPropertyChanged("Anschrift");
					this.OnAnschriftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLZ", DbType="VarChar(50)")]
		public string PLZ
		{
			get
			{
				return this._PLZ;
			}
			set
			{
				if ((this._PLZ != value))
				{
					this.OnPLZChanging(value);
					this.SendPropertyChanging();
					this._PLZ = value;
					this.SendPropertyChanged("PLZ");
					this.OnPLZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stadt", DbType="VarChar(50)")]
		public string Stadt
		{
			get
			{
				return this._Stadt;
			}
			set
			{
				if ((this._Stadt != value))
				{
					this.OnStadtChanging(value);
					this.SendPropertyChanging();
					this._Stadt = value;
					this.SendPropertyChanged("Stadt");
					this.OnStadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land", DbType="VarChar(50)")]
		public string Land
		{
			get
			{
				return this._Land;
			}
			set
			{
				if ((this._Land != value))
				{
					this.OnLandChanging(value);
					this.SendPropertyChanging();
					this._Land = value;
					this.SendPropertyChanged("Land");
					this.OnLandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_Auftrag", Storage="_Auftrag", ThisKey="Id", OtherKey="Id_Kunde")]
		public EntitySet<Auftrag> Auftrag
		{
			get
			{
				return this._Auftrag;
			}
			set
			{
				this._Auftrag.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Auftrag(Auftrag entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = this;
		}
		
		private void detach_Auftrag(Auftrag entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teilschritt")]
	public partial class Teilschritt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Zieltemperatur;
		
		private System.Nullable<int> _Delta;
		
		private string _Funktion;
		
		private System.Nullable<int> _Id_Verfahren;
		
		private EntityRef<Verfahren> _Verfahren;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnZieltemperaturChanging(System.Nullable<int> value);
    partial void OnZieltemperaturChanged();
    partial void OnDeltaChanging(System.Nullable<int> value);
    partial void OnDeltaChanged();
    partial void OnFunktionChanging(string value);
    partial void OnFunktionChanged();
    partial void OnId_VerfahrenChanging(System.Nullable<int> value);
    partial void OnId_VerfahrenChanged();
    #endregion
		
		public Teilschritt()
		{
			this._Verfahren = default(EntityRef<Verfahren>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zieltemperatur", DbType="Int")]
		public System.Nullable<int> Zieltemperatur
		{
			get
			{
				return this._Zieltemperatur;
			}
			set
			{
				if ((this._Zieltemperatur != value))
				{
					this.OnZieltemperaturChanging(value);
					this.SendPropertyChanging();
					this._Zieltemperatur = value;
					this.SendPropertyChanged("Zieltemperatur");
					this.OnZieltemperaturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delta", DbType="Int")]
		public System.Nullable<int> Delta
		{
			get
			{
				return this._Delta;
			}
			set
			{
				if ((this._Delta != value))
				{
					this.OnDeltaChanging(value);
					this.SendPropertyChanging();
					this._Delta = value;
					this.SendPropertyChanged("Delta");
					this.OnDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Funktion", DbType="VarChar(50)")]
		public string Funktion
		{
			get
			{
				return this._Funktion;
			}
			set
			{
				if ((this._Funktion != value))
				{
					this.OnFunktionChanging(value);
					this.SendPropertyChanging();
					this._Funktion = value;
					this.SendPropertyChanged("Funktion");
					this.OnFunktionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Verfahren", DbType="Int")]
		public System.Nullable<int> Id_Verfahren
		{
			get
			{
				return this._Id_Verfahren;
			}
			set
			{
				if ((this._Id_Verfahren != value))
				{
					if (this._Verfahren.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_VerfahrenChanging(value);
					this.SendPropertyChanging();
					this._Id_Verfahren = value;
					this.SendPropertyChanged("Id_Verfahren");
					this.OnId_VerfahrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Verfahren_Teilschritt", Storage="_Verfahren", ThisKey="Id_Verfahren", OtherKey="Id", IsForeignKey=true)]
		public Verfahren Verfahren
		{
			get
			{
				return this._Verfahren.Entity;
			}
			set
			{
				Verfahren previousValue = this._Verfahren.Entity;
				if (((previousValue != value) 
							|| (this._Verfahren.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Verfahren.Entity = null;
						previousValue.Teilschritt.Remove(this);
					}
					this._Verfahren.Entity = value;
					if ((value != null))
					{
						value.Teilschritt.Add(this);
						this._Id_Verfahren = value.Id;
					}
					else
					{
						this._Id_Verfahren = default(Nullable<int>);
					}
					this.SendPropertyChanged("Verfahren");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MN_VerfahrenAuftrag")]
	public partial class MN_VerfahrenAuftrag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Id_Verfahren;
		
		private System.Nullable<int> _Id_Auftrag;
		
		private System.Nullable<int> _Schritt;
		
		private EntityRef<Verfahren> _Verfahren;
		
		private EntityRef<Auftrag> _Auftrag;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_VerfahrenChanging(System.Nullable<int> value);
    partial void OnId_VerfahrenChanged();
    partial void OnId_AuftragChanging(System.Nullable<int> value);
    partial void OnId_AuftragChanged();
    partial void OnSchrittChanging(System.Nullable<int> value);
    partial void OnSchrittChanged();
    #endregion
		
		public MN_VerfahrenAuftrag()
		{
			this._Verfahren = default(EntityRef<Verfahren>);
			this._Auftrag = default(EntityRef<Auftrag>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Verfahren", DbType="Int")]
		public System.Nullable<int> Id_Verfahren
		{
			get
			{
				return this._Id_Verfahren;
			}
			set
			{
				if ((this._Id_Verfahren != value))
				{
					if (this._Verfahren.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_VerfahrenChanging(value);
					this.SendPropertyChanging();
					this._Id_Verfahren = value;
					this.SendPropertyChanged("Id_Verfahren");
					this.OnId_VerfahrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Auftrag", DbType="Int")]
		public System.Nullable<int> Id_Auftrag
		{
			get
			{
				return this._Id_Auftrag;
			}
			set
			{
				if ((this._Id_Auftrag != value))
				{
					if (this._Auftrag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AuftragChanging(value);
					this.SendPropertyChanging();
					this._Id_Auftrag = value;
					this.SendPropertyChanged("Id_Auftrag");
					this.OnId_AuftragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schritt", DbType="Int")]
		public System.Nullable<int> Schritt
		{
			get
			{
				return this._Schritt;
			}
			set
			{
				if ((this._Schritt != value))
				{
					this.OnSchrittChanging(value);
					this.SendPropertyChanging();
					this._Schritt = value;
					this.SendPropertyChanged("Schritt");
					this.OnSchrittChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Verfahren_MN_VerfahrenAuftrag", Storage="_Verfahren", ThisKey="Id_Verfahren", OtherKey="Id", IsForeignKey=true)]
		public Verfahren Verfahren
		{
			get
			{
				return this._Verfahren.Entity;
			}
			set
			{
				Verfahren previousValue = this._Verfahren.Entity;
				if (((previousValue != value) 
							|| (this._Verfahren.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Verfahren.Entity = null;
						previousValue.MN_VerfahrenAuftrag.Remove(this);
					}
					this._Verfahren.Entity = value;
					if ((value != null))
					{
						value.MN_VerfahrenAuftrag.Add(this);
						this._Id_Verfahren = value.Id;
					}
					else
					{
						this._Id_Verfahren = default(Nullable<int>);
					}
					this.SendPropertyChanged("Verfahren");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_MN_VerfahrenAuftrag", Storage="_Auftrag", ThisKey="Id_Auftrag", OtherKey="Id", IsForeignKey=true)]
		public Auftrag Auftrag
		{
			get
			{
				return this._Auftrag.Entity;
			}
			set
			{
				Auftrag previousValue = this._Auftrag.Entity;
				if (((previousValue != value) 
							|| (this._Auftrag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Auftrag.Entity = null;
						previousValue.MN_VerfahrenAuftrag.Remove(this);
					}
					this._Auftrag.Entity = value;
					if ((value != null))
					{
						value.MN_VerfahrenAuftrag.Add(this);
						this._Id_Auftrag = value.Id;
					}
					else
					{
						this._Id_Auftrag = default(Nullable<int>);
					}
					this.SendPropertyChanged("Auftrag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Verfahren")]
	public partial class Verfahren : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Beschreibung;
		
		private string _Art;
		
		private EntitySet<Teilschritt> _Teilschritt;
		
		private EntitySet<MN_VerfahrenAuftrag> _MN_VerfahrenAuftrag;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBeschreibungChanging(string value);
    partial void OnBeschreibungChanged();
    partial void OnArtChanging(string value);
    partial void OnArtChanged();
    #endregion
		
		public Verfahren()
		{
			this._Teilschritt = new EntitySet<Teilschritt>(new Action<Teilschritt>(this.attach_Teilschritt), new Action<Teilschritt>(this.detach_Teilschritt));
			this._MN_VerfahrenAuftrag = new EntitySet<MN_VerfahrenAuftrag>(new Action<MN_VerfahrenAuftrag>(this.attach_MN_VerfahrenAuftrag), new Action<MN_VerfahrenAuftrag>(this.detach_MN_VerfahrenAuftrag));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(MAX)")]
		public string Beschreibung
		{
			get
			{
				return this._Beschreibung;
			}
			set
			{
				if ((this._Beschreibung != value))
				{
					this.OnBeschreibungChanging(value);
					this.SendPropertyChanging();
					this._Beschreibung = value;
					this.SendPropertyChanged("Beschreibung");
					this.OnBeschreibungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art", DbType="VarChar(20)")]
		public string Art
		{
			get
			{
				return this._Art;
			}
			set
			{
				if ((this._Art != value))
				{
					this.OnArtChanging(value);
					this.SendPropertyChanging();
					this._Art = value;
					this.SendPropertyChanged("Art");
					this.OnArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Verfahren_Teilschritt", Storage="_Teilschritt", ThisKey="Id", OtherKey="Id_Verfahren")]
		public EntitySet<Teilschritt> Teilschritt
		{
			get
			{
				return this._Teilschritt;
			}
			set
			{
				this._Teilschritt.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Verfahren_MN_VerfahrenAuftrag", Storage="_MN_VerfahrenAuftrag", ThisKey="Id", OtherKey="Id_Verfahren")]
		public EntitySet<MN_VerfahrenAuftrag> MN_VerfahrenAuftrag
		{
			get
			{
				return this._MN_VerfahrenAuftrag;
			}
			set
			{
				this._MN_VerfahrenAuftrag.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Teilschritt(Teilschritt entity)
		{
			this.SendPropertyChanging();
			entity.Verfahren = this;
		}
		
		private void detach_Teilschritt(Teilschritt entity)
		{
			this.SendPropertyChanging();
			entity.Verfahren = null;
		}
		
		private void attach_MN_VerfahrenAuftrag(MN_VerfahrenAuftrag entity)
		{
			this.SendPropertyChanging();
			entity.Verfahren = this;
		}
		
		private void detach_MN_VerfahrenAuftrag(MN_VerfahrenAuftrag entity)
		{
			this.SendPropertyChanging();
			entity.Verfahren = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Material")]
	public partial class Material : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Datum;
		
		private string _Bunde;
		
		private string _Stahlsorte;
		
		private string _Charge;
		
		private System.Nullable<int> _Anzahl;
		
		private System.Nullable<int> _Gewicht;
		
		private System.Nullable<int> _Id_Glühung;
		
		private int _Id_Auftrag;
		
		private EntityRef<Auftrag> _Auftrag;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumChanged();
    partial void OnBundeChanging(string value);
    partial void OnBundeChanged();
    partial void OnStahlsorteChanging(string value);
    partial void OnStahlsorteChanged();
    partial void OnChargeChanging(string value);
    partial void OnChargeChanged();
    partial void OnAnzahlChanging(System.Nullable<int> value);
    partial void OnAnzahlChanged();
    partial void OnGewichtChanging(System.Nullable<int> value);
    partial void OnGewichtChanged();
    partial void OnId_GlühungChanging(System.Nullable<int> value);
    partial void OnId_GlühungChanged();
    partial void OnId_AuftragChanging(int value);
    partial void OnId_AuftragChanged();
    #endregion
		
		public Material()
		{
			this._Auftrag = default(EntityRef<Auftrag>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bunde", DbType="NChar(7)")]
		public string Bunde
		{
			get
			{
				return this._Bunde;
			}
			set
			{
				if ((this._Bunde != value))
				{
					this.OnBundeChanging(value);
					this.SendPropertyChanging();
					this._Bunde = value;
					this.SendPropertyChanged("Bunde");
					this.OnBundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stahlsorte", DbType="VarChar(20)")]
		public string Stahlsorte
		{
			get
			{
				return this._Stahlsorte;
			}
			set
			{
				if ((this._Stahlsorte != value))
				{
					this.OnStahlsorteChanging(value);
					this.SendPropertyChanging();
					this._Stahlsorte = value;
					this.SendPropertyChanged("Stahlsorte");
					this.OnStahlsorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charge", DbType="VarChar(10)")]
		public string Charge
		{
			get
			{
				return this._Charge;
			}
			set
			{
				if ((this._Charge != value))
				{
					this.OnChargeChanging(value);
					this.SendPropertyChanging();
					this._Charge = value;
					this.SendPropertyChanged("Charge");
					this.OnChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anzahl", DbType="Int")]
		public System.Nullable<int> Anzahl
		{
			get
			{
				return this._Anzahl;
			}
			set
			{
				if ((this._Anzahl != value))
				{
					this.OnAnzahlChanging(value);
					this.SendPropertyChanging();
					this._Anzahl = value;
					this.SendPropertyChanged("Anzahl");
					this.OnAnzahlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gewicht", DbType="Int")]
		public System.Nullable<int> Gewicht
		{
			get
			{
				return this._Gewicht;
			}
			set
			{
				if ((this._Gewicht != value))
				{
					this.OnGewichtChanging(value);
					this.SendPropertyChanging();
					this._Gewicht = value;
					this.SendPropertyChanged("Gewicht");
					this.OnGewichtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Glühung", DbType="Int")]
		public System.Nullable<int> Id_Glühung
		{
			get
			{
				return this._Id_Glühung;
			}
			set
			{
				if ((this._Id_Glühung != value))
				{
					this.OnId_GlühungChanging(value);
					this.SendPropertyChanging();
					this._Id_Glühung = value;
					this.SendPropertyChanged("Id_Glühung");
					this.OnId_GlühungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Auftrag", DbType="Int NOT NULL")]
		public int Id_Auftrag
		{
			get
			{
				return this._Id_Auftrag;
			}
			set
			{
				if ((this._Id_Auftrag != value))
				{
					if (this._Auftrag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AuftragChanging(value);
					this.SendPropertyChanging();
					this._Id_Auftrag = value;
					this.SendPropertyChanged("Id_Auftrag");
					this.OnId_AuftragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_Material", Storage="_Auftrag", ThisKey="Id_Auftrag", OtherKey="Id", IsForeignKey=true)]
		public Auftrag Auftrag
		{
			get
			{
				return this._Auftrag.Entity;
			}
			set
			{
				Auftrag previousValue = this._Auftrag.Entity;
				if (((previousValue != value) 
							|| (this._Auftrag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Auftrag.Entity = null;
						previousValue.Material.Remove(this);
					}
					this._Auftrag.Entity = value;
					if ((value != null))
					{
						value.Material.Add(this);
						this._Id_Auftrag = value.Id;
					}
					else
					{
						this._Id_Auftrag = default(int);
					}
					this.SendPropertyChanged("Auftrag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auftrag")]
	public partial class Auftrag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AuftragsNr;
		
		private string _ODL;
		
		private string _Art;
		
		private string _Verarbeitung;
		
		private string _Position;
		
		private string _Status;
		
		private System.Nullable<double> _Abmessung1;
		
		private System.Nullable<double> _Abmessung2;
		
		private System.Nullable<double> _FLänge;
		
		private System.Nullable<double> _WLänge;
		
		private string _Charge;
		
		private string _Stahlsorte;
		
		private string _Walzung;
		
		private System.Nullable<System.DateTime> _Auftragsdatum;
		
		private System.Nullable<System.DateTime> _Liefertermin;
		
		private string _TechnischeAnmerkungen;
		
		private string _Bemerkungen;
		
		private System.Nullable<int> _SägeProgramm;
		
		private System.Nullable<double> _Anlasstemparartur;
		
		private System.Nullable<bool> _Wichtig;
		
		private System.Nullable<int> _Id_Kunde;
		
		private System.Nullable<int> _Id_Bestimmungsort;
		
		private EntitySet<MN_VerfahrenAuftrag> _MN_VerfahrenAuftrag;
		
		private EntitySet<Material> _Material;
		
		private EntityRef<Bestimmungsort> _Bestimmungsort;
		
		private EntityRef<Kunde> _Kunde;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAuftragsNrChanging(string value);
    partial void OnAuftragsNrChanged();
    partial void OnODLChanging(string value);
    partial void OnODLChanged();
    partial void OnArtChanging(string value);
    partial void OnArtChanged();
    partial void OnVerarbeitungChanging(string value);
    partial void OnVerarbeitungChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnAbmessung1Changing(System.Nullable<double> value);
    partial void OnAbmessung1Changed();
    partial void OnAbmessung2Changing(System.Nullable<double> value);
    partial void OnAbmessung2Changed();
    partial void OnFLängeChanging(System.Nullable<double> value);
    partial void OnFLängeChanged();
    partial void OnWLängeChanging(System.Nullable<double> value);
    partial void OnWLängeChanged();
    partial void OnChargeChanging(string value);
    partial void OnChargeChanged();
    partial void OnStahlsorteChanging(string value);
    partial void OnStahlsorteChanged();
    partial void OnWalzungChanging(string value);
    partial void OnWalzungChanged();
    partial void OnAuftragsdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnAuftragsdatumChanged();
    partial void OnLieferterminChanging(System.Nullable<System.DateTime> value);
    partial void OnLieferterminChanged();
    partial void OnTechnischeAnmerkungenChanging(string value);
    partial void OnTechnischeAnmerkungenChanged();
    partial void OnBemerkungenChanging(string value);
    partial void OnBemerkungenChanged();
    partial void OnSägeProgrammChanging(System.Nullable<int> value);
    partial void OnSägeProgrammChanged();
    partial void OnAnlasstempararturChanging(System.Nullable<double> value);
    partial void OnAnlasstempararturChanged();
    partial void OnWichtigChanging(System.Nullable<bool> value);
    partial void OnWichtigChanged();
    partial void OnId_KundeChanging(System.Nullable<int> value);
    partial void OnId_KundeChanged();
    partial void OnId_BestimmungsortChanging(System.Nullable<int> value);
    partial void OnId_BestimmungsortChanged();
    #endregion
		
		public Auftrag()
		{
			this._MN_VerfahrenAuftrag = new EntitySet<MN_VerfahrenAuftrag>(new Action<MN_VerfahrenAuftrag>(this.attach_MN_VerfahrenAuftrag), new Action<MN_VerfahrenAuftrag>(this.detach_MN_VerfahrenAuftrag));
			this._Material = new EntitySet<Material>(new Action<Material>(this.attach_Material), new Action<Material>(this.detach_Material));
			this._Bestimmungsort = default(EntityRef<Bestimmungsort>);
			this._Kunde = default(EntityRef<Kunde>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuftragsNr", DbType="VarChar(10)")]
		public string AuftragsNr
		{
			get
			{
				return this._AuftragsNr;
			}
			set
			{
				if ((this._AuftragsNr != value))
				{
					this.OnAuftragsNrChanging(value);
					this.SendPropertyChanging();
					this._AuftragsNr = value;
					this.SendPropertyChanged("AuftragsNr");
					this.OnAuftragsNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODL", DbType="VarChar(10)")]
		public string ODL
		{
			get
			{
				return this._ODL;
			}
			set
			{
				if ((this._ODL != value))
				{
					this.OnODLChanging(value);
					this.SendPropertyChanging();
					this._ODL = value;
					this.SendPropertyChanged("ODL");
					this.OnODLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art", DbType="VarChar(50)")]
		public string Art
		{
			get
			{
				return this._Art;
			}
			set
			{
				if ((this._Art != value))
				{
					this.OnArtChanging(value);
					this.SendPropertyChanging();
					this._Art = value;
					this.SendPropertyChanged("Art");
					this.OnArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verarbeitung", DbType="VarChar(50)")]
		public string Verarbeitung
		{
			get
			{
				return this._Verarbeitung;
			}
			set
			{
				if ((this._Verarbeitung != value))
				{
					this.OnVerarbeitungChanging(value);
					this.SendPropertyChanging();
					this._Verarbeitung = value;
					this.SendPropertyChanged("Verarbeitung");
					this.OnVerarbeitungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(5)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abmessung1", DbType="Float")]
		public System.Nullable<double> Abmessung1
		{
			get
			{
				return this._Abmessung1;
			}
			set
			{
				if ((this._Abmessung1 != value))
				{
					this.OnAbmessung1Changing(value);
					this.SendPropertyChanging();
					this._Abmessung1 = value;
					this.SendPropertyChanged("Abmessung1");
					this.OnAbmessung1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abmessung2", DbType="Float")]
		public System.Nullable<double> Abmessung2
		{
			get
			{
				return this._Abmessung2;
			}
			set
			{
				if ((this._Abmessung2 != value))
				{
					this.OnAbmessung2Changing(value);
					this.SendPropertyChanging();
					this._Abmessung2 = value;
					this.SendPropertyChanged("Abmessung2");
					this.OnAbmessung2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLänge", DbType="Float")]
		public System.Nullable<double> FLänge
		{
			get
			{
				return this._FLänge;
			}
			set
			{
				if ((this._FLänge != value))
				{
					this.OnFLängeChanging(value);
					this.SendPropertyChanging();
					this._FLänge = value;
					this.SendPropertyChanged("FLänge");
					this.OnFLängeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WLänge", DbType="Float")]
		public System.Nullable<double> WLänge
		{
			get
			{
				return this._WLänge;
			}
			set
			{
				if ((this._WLänge != value))
				{
					this.OnWLängeChanging(value);
					this.SendPropertyChanging();
					this._WLänge = value;
					this.SendPropertyChanged("WLänge");
					this.OnWLängeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charge", DbType="VarChar(5)")]
		public string Charge
		{
			get
			{
				return this._Charge;
			}
			set
			{
				if ((this._Charge != value))
				{
					this.OnChargeChanging(value);
					this.SendPropertyChanging();
					this._Charge = value;
					this.SendPropertyChanged("Charge");
					this.OnChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stahlsorte", DbType="VarChar(20)")]
		public string Stahlsorte
		{
			get
			{
				return this._Stahlsorte;
			}
			set
			{
				if ((this._Stahlsorte != value))
				{
					this.OnStahlsorteChanging(value);
					this.SendPropertyChanging();
					this._Stahlsorte = value;
					this.SendPropertyChanged("Stahlsorte");
					this.OnStahlsorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Walzung", DbType="VarChar(20)")]
		public string Walzung
		{
			get
			{
				return this._Walzung;
			}
			set
			{
				if ((this._Walzung != value))
				{
					this.OnWalzungChanging(value);
					this.SendPropertyChanging();
					this._Walzung = value;
					this.SendPropertyChanged("Walzung");
					this.OnWalzungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auftragsdatum", DbType="Date")]
		public System.Nullable<System.DateTime> Auftragsdatum
		{
			get
			{
				return this._Auftragsdatum;
			}
			set
			{
				if ((this._Auftragsdatum != value))
				{
					this.OnAuftragsdatumChanging(value);
					this.SendPropertyChanging();
					this._Auftragsdatum = value;
					this.SendPropertyChanged("Auftragsdatum");
					this.OnAuftragsdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liefertermin", DbType="Date")]
		public System.Nullable<System.DateTime> Liefertermin
		{
			get
			{
				return this._Liefertermin;
			}
			set
			{
				if ((this._Liefertermin != value))
				{
					this.OnLieferterminChanging(value);
					this.SendPropertyChanging();
					this._Liefertermin = value;
					this.SendPropertyChanged("Liefertermin");
					this.OnLieferterminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechnischeAnmerkungen", DbType="VarChar(MAX)")]
		public string TechnischeAnmerkungen
		{
			get
			{
				return this._TechnischeAnmerkungen;
			}
			set
			{
				if ((this._TechnischeAnmerkungen != value))
				{
					this.OnTechnischeAnmerkungenChanging(value);
					this.SendPropertyChanging();
					this._TechnischeAnmerkungen = value;
					this.SendPropertyChanged("TechnischeAnmerkungen");
					this.OnTechnischeAnmerkungenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bemerkungen", DbType="VarChar(MAX)")]
		public string Bemerkungen
		{
			get
			{
				return this._Bemerkungen;
			}
			set
			{
				if ((this._Bemerkungen != value))
				{
					this.OnBemerkungenChanging(value);
					this.SendPropertyChanging();
					this._Bemerkungen = value;
					this.SendPropertyChanged("Bemerkungen");
					this.OnBemerkungenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SägeProgramm", DbType="Int")]
		public System.Nullable<int> SägeProgramm
		{
			get
			{
				return this._SägeProgramm;
			}
			set
			{
				if ((this._SägeProgramm != value))
				{
					this.OnSägeProgrammChanging(value);
					this.SendPropertyChanging();
					this._SägeProgramm = value;
					this.SendPropertyChanged("SägeProgramm");
					this.OnSägeProgrammChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anlasstemparartur", DbType="Float")]
		public System.Nullable<double> Anlasstemparartur
		{
			get
			{
				return this._Anlasstemparartur;
			}
			set
			{
				if ((this._Anlasstemparartur != value))
				{
					this.OnAnlasstempararturChanging(value);
					this.SendPropertyChanging();
					this._Anlasstemparartur = value;
					this.SendPropertyChanged("Anlasstemparartur");
					this.OnAnlasstempararturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wichtig", DbType="Bit")]
		public System.Nullable<bool> Wichtig
		{
			get
			{
				return this._Wichtig;
			}
			set
			{
				if ((this._Wichtig != value))
				{
					this.OnWichtigChanging(value);
					this.SendPropertyChanging();
					this._Wichtig = value;
					this.SendPropertyChanged("Wichtig");
					this.OnWichtigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Kunde", DbType="Int")]
		public System.Nullable<int> Id_Kunde
		{
			get
			{
				return this._Id_Kunde;
			}
			set
			{
				if ((this._Id_Kunde != value))
				{
					if (this._Kunde.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_KundeChanging(value);
					this.SendPropertyChanging();
					this._Id_Kunde = value;
					this.SendPropertyChanged("Id_Kunde");
					this.OnId_KundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Bestimmungsort", DbType="Int")]
		public System.Nullable<int> Id_Bestimmungsort
		{
			get
			{
				return this._Id_Bestimmungsort;
			}
			set
			{
				if ((this._Id_Bestimmungsort != value))
				{
					if (this._Bestimmungsort.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_BestimmungsortChanging(value);
					this.SendPropertyChanging();
					this._Id_Bestimmungsort = value;
					this.SendPropertyChanged("Id_Bestimmungsort");
					this.OnId_BestimmungsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_MN_VerfahrenAuftrag", Storage="_MN_VerfahrenAuftrag", ThisKey="Id", OtherKey="Id_Auftrag")]
		public EntitySet<MN_VerfahrenAuftrag> MN_VerfahrenAuftrag
		{
			get
			{
				return this._MN_VerfahrenAuftrag;
			}
			set
			{
				this._MN_VerfahrenAuftrag.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Auftrag_Material", Storage="_Material", ThisKey="Id", OtherKey="Id_Auftrag")]
		public EntitySet<Material> Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				this._Material.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bestimmungsort_Auftrag", Storage="_Bestimmungsort", ThisKey="Id_Bestimmungsort", OtherKey="Id", IsForeignKey=true)]
		public Bestimmungsort Bestimmungsort
		{
			get
			{
				return this._Bestimmungsort.Entity;
			}
			set
			{
				Bestimmungsort previousValue = this._Bestimmungsort.Entity;
				if (((previousValue != value) 
							|| (this._Bestimmungsort.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bestimmungsort.Entity = null;
						previousValue.Auftrag.Remove(this);
					}
					this._Bestimmungsort.Entity = value;
					if ((value != null))
					{
						value.Auftrag.Add(this);
						this._Id_Bestimmungsort = value.Id;
					}
					else
					{
						this._Id_Bestimmungsort = default(Nullable<int>);
					}
					this.SendPropertyChanged("Bestimmungsort");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_Auftrag", Storage="_Kunde", ThisKey="Id_Kunde", OtherKey="Id", IsForeignKey=true)]
		public Kunde Kunde
		{
			get
			{
				return this._Kunde.Entity;
			}
			set
			{
				Kunde previousValue = this._Kunde.Entity;
				if (((previousValue != value) 
							|| (this._Kunde.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kunde.Entity = null;
						previousValue.Auftrag.Remove(this);
					}
					this._Kunde.Entity = value;
					if ((value != null))
					{
						value.Auftrag.Add(this);
						this._Id_Kunde = value.Id;
					}
					else
					{
						this._Id_Kunde = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kunde");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MN_VerfahrenAuftrag(MN_VerfahrenAuftrag entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = this;
		}
		
		private void detach_MN_VerfahrenAuftrag(MN_VerfahrenAuftrag entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = null;
		}
		
		private void attach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = this;
		}
		
		private void detach_Material(Material entity)
		{
			this.SendPropertyChanging();
			entity.Auftrag = null;
		}
	}
}
#pragma warning restore 1591
